baseURL: https://www.divector.com/
languageCode: ru
defaultContentLanguage: ru
publishDir: "docs"

theme: "PaperMod"
title: "divector.com"
copyright: "@ 2021 [–ò—Å—Ü–µ–ª–∏ —Å–≤–æ—é –¥—É—à—É. –ú–µ—Ç–æ–¥ SLLS](https://www.divector.com/)"
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-203355573-1

# https://github.com/adityatelange/hugo-PaperMod/wiki/Variables
params:
  env: production
  # homeInfoParams:
  #   Title: "–£—Ç–∏ –ø—É—Ç–∏ ü¶Ü"
  #   Content: Welcome to my blog

  description: "–ò—Å—Ü–µ–ª–∏ —Å–≤–æ—é –¥—É—à—É. –ú–µ—Ç–æ–¥ SLLS."
  keywords: [human design, –∏–∑–±–∞–≤–ª–µ–Ω–∏–µ –æ—Ç —Å—Ç—Ä–∞–¥–∞–Ω–∏–π, –∞—Å—Ç—Ä–æ–ª–æ–≥–∏—è, human design, –ø—Å–∏—Ö–æ–ª–æ–≥–∏—è, –Ω—É–º–µ—Ä–æ–ª–æ–≥–∏—è, –¥–∏–∞–≥–Ω–æ—Å—Ç–∏–∫–∞, –¥–∂–π–æ—Ç–∏—à, –≥–µ–Ω–Ω—ã–µ –∫–ª—é—á–∏, –¥–∏–∑–∞–π–Ω —á–µ–ª–æ–≤–µ–∫–∞, —Ç–∞—Ä–æ, —á–∞–∫—Ä—ã —á–µ–ª–æ–≤–µ–∫–∞]
  author: –°–≤–µ—Ç–õ–∞–Ω–∞ –õ—é—Å–∏—è –®–∞–Ω—ç
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2006-01-02"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  profileMode:
    enabled: true # needs to be explicitly set
    title: –ò—Å—Ü–µ–ª–∏ —Å–≤–æ—é –¥—É—à—É
    subtitle: "–ú–µ—Ç–æ–¥ SLLS"
    # imageUrl: "<img location>"
    # imageWidth: 120
    # imageHeight: 120
    # imageTitle: my image
    buttons:
      - name: –û –ø—Ä–æ–µ–∫—Ç–µ
        url: about
      - name: –£—Å–ª—É–≥–∏
        url: services

  socialIcons:
    - name: telegram
      url: "https://t.me/divector"
    - name: instagram
      url: "https://instagram.com/mydivector"
    - name: email
      url: "mailto:hq@divector.com"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

menu:
  main:
    - identifier: about
      name: –û –ø—Ä–æ–µ–∫—Ç–µ
      url: /about/
      weight: 10
    - identifier: services
      name: –£—Å–ª—É–≥–∏
      url: /services/
      weight: 11
    - identifier: search
      name: –ü–æ–∏—Å–∫
      url: /search/
      weight: 20
    - identifier: archives
      name: –°—Ç–∞—Ç—å–∏
      url: /archives/
      weight: 30
    # - identifier: tags
    #   name: –ö–∞—Ç–µ–≥–æ—Ä–∏–∏
    #   url: /tags/
    #   weight: 20
    - identifier: contacts
      name: –ö–æ–Ω—Ç–∞–∫—Ç—ã
      url: /contacts/
      weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
